version: 2

build:
    image: latest

python:
    version: {{cookiecutter.python.versions | min}}
    install:
        - method: pip
          path: .
          extra_requirements:
              - docs

sphinx:
    fail_on_warning: true
